wireplumber.components = [
  {
    name = odin3-speaker-route-unity.lua
    type = script/lua
    provides = hooks.odin3-speaker-route-unity
  }
]

wireplumber.profiles = {
  main = {
    hooks.odin3-speaker-route-unity = required
  }
}
